### ISSUE TITLE
Desarrollo del API de información familiar, específicamente el esquema informacion familiar. 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/informacion_familiar_crud#1]
Creación del CRUD para el modelo de datos del esquema informacion familiar establecido en el [modelo](https://drive.google.com/drive/folders/1IvGNEFmHex3UHw3kyEyQelewUc8OOEBp), el API debe cumplir con los siguientes requerimientos:

- [x] El crud debe cumplir con los lineamientos de la Oficina asesora de sistemas.
- [x] El crud debe contar con el refactor, para que las respuestas sean en formato Json.
- [x] Comprobar si la Api funciona correctamente con Swagger.

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se desarrolla el api crud para el modelo en la rama [dev](https://github.com/udistrital/informacion_familiar_crud), se espera revision tecnica por parte de @mafeave

**Comment by mafeave** [comment]
Se verifica API generada: 
- auto y relatedsel()
- variables de configuración
- refactoring para rtas 
- .gitignore
