### ISSUE TITLE
Ajuste modelo información familiar

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/informacion_familiar_crud#2]
Se debe ajustar el modelo desarrollado en la [Isuues](https://github.com/udistrital/campus_cliente/issues/200), para poder manejar la información de contacto de los acudientes solicitado en el proceso de inscripción de aspirantes. El modelo debe cumplir con los siguientes requerimientos:

- [x] Debe ser lo mas general posible para posible futuros cambios del sistema.
- [x] El modelo debe poder registrar la información determinada en el levantamiento de requerimientos.
- [x] El modelo debe ser desarrollado en la herramienta pgmodeler.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se Inicia el proceso de diseño y ajuste del modelo

**Comment by fabianbarreto02** [comment]
Se realiza el ajuste del modelo para poder almacenar la información solicitada en el formulario del proceso de inscripción del aspiante, queda pendiente revisión por parte del arquitecto @jairolh  y el DBA  @fnrojash el modelo diseñado es el siguiente:

![Captura de Pantalla 2019-08-16 a la(s) 10 57 50 a  m](https://user-images.githubusercontent.com/43799065/63180849-b9c3b300-c014-11e9-8313-c3d73325cb5d.png)

**Comment by fabianbarreto02** [comment]
se espera revisión por parte de lider técnica @mafeave

**Comment by mafeave** [comment]
Se verifica ajuste en el modelo para contemplar información correspondiente a los acudientes, queda pendiente la revisión con DBAs y Arquitectos

**Comment by mafeave** [comment]
De la reunión realizada para la revisión del modelo por parte de los Arquitectos y DBAs, quedan las siguientes observaciones:
- Cambiar el nombre de la tabla acudiente por contacto_familiar

**Comment by fabianbarreto02** [comment]
Se realizan los ajustes del modelo como se acordo en la reunion.

![Captura de Pantalla 2019-08-22 a la(s) 10 15 04 a  m](https://user-images.githubusercontent.com/43799065/63526874-bd987f00-c4c5-11e9-8c8e-30efd136599b.png)

**Comment by fabianbarreto02** [comment]
Se espera revisión por parte de @jairolh  y @fnrojash para aprobación del modelo.

**Comment by jairolh** [comment]
Se verifica la corrección de los ajustes solicitados.
