### ISSUE TITLE
Ajuste API información familiar por modificaciones del modelo

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/informacion_familiar_crud#3]
Se debe Ajusta el api ya desarrollado por cambios del modelo establecidos  en la [Issue](https://github.com/udistrital/informacion_familiar_crud/issues/2), este modelo debe cumplir con los siguientes requerimientos:

- [x] Debe ser lo mas general posible para posible futuros cambios del sistema.
- [x] El API debe poder registrar la información el acudiente del aspirante.
- [x]  Debe realizarce prueba con swagger para revisar el correcto funcionamiento del api.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia porceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se espera revisión por parte de la lider técnica @mafeave

**Comment by mafeave** [comment]
Hacer pull request a dev
